### ISSUE TITLE
Stack deployment completes successfully but there is infrastrucutre missing

### ISSUE THREAD

**Issue by EricSEkong** [awslabs/aws-perspective#235]
**Describe the bug**
I've tried to deploy a modified version of the v1.1.2 template. The modifications are limited to adding a permissions boundary to the Globals block 

```
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS,DELETE,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
  Function:
    Runtime: nodejs12.x
    Environment:
      Variables:
        VERSION: v1.1.2
    PermissionsBoundary: arn:aws:iam::082880109190:policy/ccoe/js-developer
```
and the following roles `LambdaExecutionRole`, `ApiGatewayCloudWatchLogsRole`, `PerspectiveAppSyncLoggingRole` and `PerspectiveDiscoveryRole`
The permissions boundary policy can be found here: https://gist.github.com/EricSEkong/8186ebb246eadfb9897201795372c7d1

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an IAM policy in AWS account (gist linked)
2. Modify template v1.1.2 as described above to include reference to the policy in set 1
3. Deploy stack

**Expected behaviour**
Clicking on URL of `PerspectiveWebUiApiUrl` output in the CFN console will open AWS Perspective web app
